### ISSUE TITLE
How can we get the dataset

### ISSUE THREAD

**Issue by ilml** [alicex2020/Mandarin-Tone-Classification#1]
It seems that we can't download it from the website.
Could you please me tell me how to get that?
Thank you very much!

**Comment by dpny518** [comment]
wget https://tone.lib.msu.edu/tone/6386 -o 6386.mp3
....
https://tone.lib.msu.edu/tone/9851 -o 9851.mp3

How can we get the labels such as a1 automatically while downloading so its like this

**Comment by alicex2020** [comment]
The original bulk download link was here https://listings.lib.msu.edu/toneperfect.
It seems that it's since been taken down. Please email me at alixue.16@gmail.com and I will be happy to email the dataset to you.
